### ISSUE TITLE
quarryplus' workbenchplus crashes the game when placed

### ISSUE THREAD

**Issue by Jaalte** [q13er/gary8#8]
big oof
may also crash the server, you should check if there's a crash log from around 4:45pm on 5/30

[crash-2020-05-30_14.45.55-client.txt](https://github.com/q13er/gary8/files/4706693/crash-2020-05-30_14.45.55-client.txt)

**Comment by q13er** [comment]
I'm just gonna add IC2

**Comment by q13er** [comment]
This ended up breaking thermal recycling because ic2 and thermal recycling add the same API for recycling, so I removed thermal recycling. This will cause lighting bugs around the world where we had the piles of rubble and vending machines unfortunately. This is a sacrifice I am willing to make though because it will mostly only impact our already lit caves. In unlit caves, they will be as dark as the cave around them, so no big difference. At least this also removes the earthworms.

**Comment by q13er** [comment]
Fixedboi
